### ISSUE TITLE
I can't change the date formatting

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [thundermiracle/gatsby-simple-blog#198]
I have changed all of the date formatting to `date(formatString: "YYYY-MM-DD")` in every place in the project, 
but it still outputs the month name instead of the month number.

It works fine in the localhost:8000/___graphql which is weird.

**Comment by thundermiracle** [comment]
You should not change the date format in GraqhQL's query because this is a multilingual site template.

The format of the date is depended on the language you defined here: [https://github.com/thundermiracle/gatsby-simple-blog#i18n](https://github.com/thundermiracle/gatsby-simple-blog#i18n), and automatically fomatted by the`formatPostDate` function: [https://github.com/thundermiracle/gatsby-simple-blog/blob/master/src/utils/helpers.js#L11-L19](https://github.com/thundermiracle/gatsby-simple-blog/blob/master/src/utils/helpers.js#L11-L19)

The simple flow:
get date from GraphpQL
↓
get `lang` by URL/config
↓
format date from GraphQL by `date. toLocaleDateString `

So my suggestion is to check the configurations of i18n is correctly set or not.

**Comment by WatheqAlshowaiter** [comment]
Thank you so much for your help.

I changed the month formating to 'numeric'. I want to make 2 decimal places all the time like '01' , '02' etc.

how can I do that?

**Comment by thundermiracle** [comment]
Using `2-digit` instead of `numeric` shall solve your problem.

```js
new Date("2020/2/2").toLocaleDateString("en", { year: "numeric", month: "2-digit", day: "2-digit" })
// 02/02/2020
```

**Comment by WatheqAlshowaiter** [comment]
@thundermiracle 
Thank you so much for your response!
